apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-spring-deployment
  labels:
    app: todo-spring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-spring
  template:
    metadata:
      labels:
        app: todo-spring
    spec:
      containers:
      - name: todo-spring-container
        image: deepakchoursiya/todo-spring
        ports:
        - containerPort: 8080
